AllCops:
  TargetRubyVersion: 2.4

inherit_from:
  - .rubocop_todo.yml

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
