app = "bitter-sunset-340"
kill_signal = "SIGINT"
kill_timeout = 5

[processes]
  cron = "cron -f"

[env]
  BUNDLE_WITHOUT = "development:test"
  GIT_HOST = "git@github.com:arkadiyt/bounty-targets-data.git"
